<?php
/**
 * This file is part of ZeroBoiler, licensed under the MIT license.
 */

declare(strict_types=1);

namespace ZeroBoiler\Analytics\DTO;

/**
 * Immutable DTO representing an analytics insight.
 *
 * Generated by AnalyticsInsightsService from aggregated event data.
 * Insights represent automated observations about user behavior patterns,
 * trending events, conversion opportunities, and anomaly detection results.
 *
 * @phpstan-type InsightType 'trending'|'anomaly'|'funnel_drop'|'opportunity'|'warning'
 *
 * @since 1.0.0
 */
final readonly class AnalyticsInsight
{
    /**
     * @param  InsightType  $type  Category of insight
     * @param  string  $title  Human-readable insight title
     * @param  string  $description  Detailed description of the insight
     * @param  float  $score  Impact score (0.0-1.0, higher = more significant)
     * @param  string|null  $category  Event category (ecommerce, saas, engagement)
     * @param  string|null  $eventName  Related event name (if applicable)
     * @param  array<string, mixed>  $metadata  Additional context (trend data, comparisons, etc.)
     * @param  \DateTimeImmutable|null  $observedAt  When the insight was detected
     * @param  string|null  $recommendation  Actionable recommendation
     */
    public function __construct(
        public string $type,
        public string $title,
        public string $description,
        public float $score,
        public ?string $category = null,
        public ?string $eventName = null,
        public array $metadata = [],
        public ?\DateTimeImmutable $observedAt = null,
        public ?string $recommendation = null,
    ) {}

    /**
     * Create from array representation.
     *
     * @param  array{type?: string, title?: string, description?: string, score?: float, category?: string|null, event_name?: string|null, metadata?: array<string, mixed>, observed_at?: string|null, recommendation?: string|null}  $data
     */
    public static function fromArray(array $data): self
    {
        return new self(
            type: is_string($data['type'] ?? null) ? $data['type'] : 'trending',
            title: is_string($data['title'] ?? null) ? $data['title'] : '',
            description: is_string($data['description'] ?? null) ? $data['description'] : '',
            score: is_numeric($data['score'] ?? null) ? (float) ($data['score']) : 0.0,
            category: is_string($data['category'] ?? null) ? $data['category'] : null,
            eventName: is_string($data['event_name'] ?? null) ? $data['event_name'] : null,
            metadata: is_array($data['metadata'] ?? null) ? $data['metadata'] : [],
            observedAt: isset($data['observed_at']) && is_string($data['observed_at'])
                ? \DateTimeImmutable::createFromFormat('Y-m-d\TH:i:s', $data['observed_at']) ?: null
                : null,
            recommendation: is_string($data['recommendation'] ?? null) ? $data['recommendation'] : null,
        );
    }

    /**
     * Convert to array representation.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        return [
            'type' => $this->type,
            'title' => $this->title,
            'description' => $this->description,
            'score' => round($this->score, 4),
            'category' => $this->category,
            'event_name' => $this->eventName,
            'metadata' => $this->metadata,
            'observed_at' => $this->observedAt?->format('Y-m-d\TH:i:s'),
            'recommendation' => $this->recommendation,
        ];
    }
}
