<?php
/**
 * This file is part of ZeroBoiler, licensed under the MIT license.
 */

declare(strict_types=1);

namespace ZeroBoiler\Analytics\Facades;

use Illuminate\Support\Facades\Facade;
use ZeroBoiler\Analytics\DTO\AnalyticsEvent;
use ZeroBoiler\Analytics\DTO\ConsentState;
use ZeroBoiler\Analytics\Trackers\GA4Tracker;
use ZeroBoiler\Analytics\Trackers\GTMTracker;
use ZeroBoiler\Analytics\Trackers\MetaPixelTracker;
use ZeroBoiler\Analytics\Trackers\PlausibleTracker;
use ZeroBoiler\Analytics\Trackers\PosthogTracker;

/**
 * @method static void track(string $eventName, array<string, mixed> $params = [])
 * @method static void trackEvent(AnalyticsEvent $event)
 * @method static void trackEcommerce(string $eventName, array<string, mixed> $data = [], array<string, mixed> $params = [])
 * @method static void purchase(string $transactionId, float $value, array<int, array<string, mixed>> $items = [], array<string, mixed> $params = [])
 * @method static void identify(string $userId, ?string $clientId = null, array<string, mixed> $traits = [])
 * @method static void screenView(string $screenName, ?string $screenClass = null, array<string, mixed> $params = [])
 * @method static void pageView(string $title = '', string $location = '', string $referrer = '', array<string, mixed> $params = [])
 * @method static void serverSidePageView(string $title = '', string $location = '', string $referrer = '', string|null $clientId = null, string|null $userId = null, array<string, mixed> $params = [])
 * @method static void abTestExposure(string $experimentId, string $variantId, array<string, mixed> $params = [])
 * @method static void notification(string $channel, string $action, ?string $notificationType = null, array<string, mixed> $params = [])
 * @method static void trackAsync(string $eventName, array<string, mixed> $params = [])
 * @method static bool trackDebounced(string $eventName, array<string, mixed> $params = [])
 * @method static bool trackOnce(string $eventName, array<string, mixed> $params = [])
 * @method static \ZeroBoiler\Analytics\Services\AnalyticsEventBuffer eventBuffer()
 * @method static void setUserProperties(array<string, mixed> $properties, string|null $userId = null)
 * @method static void alias(string $previousId, string $newId)
 * @method static void logout(string|null $method = null, array<string, mixed> $params = [])
 * @method static void trialEnd(string $outcome, string|null $planName = null, array<string, mixed> $params = [])
 * @method static void trialConverted(string|null $planName = null, float|null $amount = null, string $currency = 'USD', array<string, mixed> $params = [])
 * @method static void planDowngrade(string $fromPlan, string $toPlan, array<string, mixed> $params = [])
 * @method static void wishlist(array<string, mixed> $item, array<string, mixed> $params = [])
 * @method static void selectItem(array<int, array<string, mixed>> $items = [], string|null $itemListId = null, string|null $itemListName = null, array<string, mixed> $params = [])
 * @method static void selectPromotion(string|null $promotionId = null, string|null $promotionName = null, string|null $creativeName = null, string|null $creativeSlot = null, array<string, mixed> $params = [])
 * @method static void viewPromotion(string|null $promotionId = null, string|null $promotionName = null, string|null $creativeName = null, string|null $creativeSlot = null, array<string, mixed> $params = [])
 * @method static void subscriptionRenewal(string|null $planName = null, float|null $amount = null, string $currency = 'USD', string|null $billingCycle = null, array<string, mixed> $params = [])
 * @method static bool directDispatch(AnalyticsEvent $event)
 * @method static array{content_ids: list<string>, contents: array<int, array<string, mixed>>, num_items: int} formatEcommerceForMeta(array<int, array<string, mixed>> $items)
 * @method static string headScripts()
 * @method static string bodyScripts()
 * @method static void push(array<string, mixed> $data)
 * @method static GA4Tracker ga4()
 * @method static GTMTracker gtm()
 * @method static MetaPixelTracker meta()
 * @method static PlausibleTracker plausible()
 * @method static PosthogTracker posthog()
 * @method static \ZeroBoiler\Analytics\Trackers\WebhookTracker webhook()
 * @method static \ZeroBoiler\Analytics\Trackers\MixpanelTracker mixpanel()
 * @method static \ZeroBoiler\Analytics\Trackers\AmplitudeTracker amplitude()
 * @method static void trackSaaSIdentity(string $userId, string $clientId, array<string, mixed> $traits = [])
 * @method static void setConsent(ConsentState $state)
 * @method static void grantConsent()
 * @method static void denyConsent()
 * @method static ConsentState getConsent()
 * @method static bool isDebug()
 * @method static bool shouldLogEvents()
 * @method static void setDebug(bool $enabled)
 * @method static void resetIdentity()
 * @method static array{ecommerce: int, saas: int, engagement: int, marketing: int, infrastructure: int, security: int, uptime: int, total: int} eventCatalogSummary()
 * @method static bool eventExists(string $eventName)
 * @method static string|null eventCategory(string $eventName)
 * @method static array{valid: bool, errors: list<array{field: string, rule: string, message: string}>, coerced_params: array<string, mixed>, coercions: int} validateEvent(string $eventName, array<string, mixed> $params)
 * @method static int totalEventCount()
 * @method static void trackError(string $message, string|null $source = null, int|null $line = null, array<string, mixed> $params = [])
 * @method static void mrr(float $amount, int $subscribers = 0, array<string, mixed> $params = [])
 * @method static void trackRevenue(float $amount, string $currency = 'USD', string $revenueType = 'one_time', array<string, mixed> $params = [])
 * @method static array{checksum: string, event_name: string, amount: float} trackRevenueEvent(string $eventName, float $amount, string $currency = 'USD', string|null $transactionId = null, array<string, mixed> $params = [])
 * @method static bool isTrackingAllowed(string|null $userId = null, string|null $clientId = null)
 * @method static void optOut(string $userId)
 * @method static void optIn(string $userId)
 * @method static void suppressClient(string $clientId)
 * @method static bool transferClientToUser(string $clientId, string $userId)
 * @method static void interceptBefore(callable $interceptor)
 * @method static void interceptAfter(callable $interceptor)
 * @method static \ZeroBoiler\Analytics\EventInterceptorRegistry interceptors()
 * @method static array{event_counts: array<string, int>, total_events: int, total_value: float, first_seen: string|null, last_seen: string|null, funnel_steps: array<string, bool>, engagement_score: float, plan: string|null, traits: array<string, mixed>} getProfile(string $userId)
 * @method static array{user_id: string, total_events: int, lifetime_value: float, first_seen: string|null, last_seen: string|null, engagement_score: float, plan: string|null, event_types: int, funnel_steps_completed: int, traits: array<string, mixed>} getProfileSummary(string $userId)
 * @method static void inviteSent(string $inviteType, string|null $role = null, array<string, mixed> $params = [])
 * @method static void integrationConnected(string $integrationName, array<string, mixed> $params = [])
 * @method static void fileDownload(string $fileName, string|null $fileType = null, array<string, mixed> $params = [])
 * @method static void videoPlay(string $videoTitle, string|null $videoProvider = null, array<string, mixed> $params = [])
 * @method static array{valid: bool, errors: list<string>, warnings: list<string>} validateCatalog()
 * @method static string version()
 * @method static array<string, array{enabled: bool, id?: string}> providerSummary()
 * @method static \ZeroBoiler\Analytics\AnalyticsMetrics metrics()
 * @method static array{events: int, dispatched: int, failed: int, success_rate: float, top_event: string|null} reportSummary()
 * @method static array{enabled: bool, strategy: string, total: int, buffered: int, max_size: int, storage_path: string, utilization: float} dlqSummary()
 * @method static string resolveEventName(string $name)
 * @method static void trackWithAlias(string $name, array<string, mixed> $params = [])
 * @method static void featureAdopted(string $featureName, ?string $category = null, array<string, mixed> $params = [])
 * @method static void expansionRevenue(float $amount, string $source, ?string $currency = null)
 * @method static void exportEvent(string $format, ?string $resource = null, ?int $recordCount = null, array<string, mixed> $params = [])
 * @method static void importEvent(string $format, ?string $resource = null, ?int $recordCount = null, ?bool $success = null, array<string, mixed> $params = [])
 * @method static void trackFunnel(string $funnelName, string $stepName, ?int $stepNumber = null, ?int $totalSteps = null, array<string, mixed> $params = [])
 * @method static array{funnel_name: string, step_name: string, step_number: int, total_steps: int, completion_pct: float, is_complete: bool, is_advancement: bool, is_regression: bool, elapsed_seconds: float|null, previous_step: string|null, previous_step_number: int|null, first_seen: string|null, last_updated: string} funnelProgress(string $funnelName, string $stepName, string $identity, int $stepNumber, int $totalSteps, array<string, mixed> $params = [])
 * @method static array{events: list<array<string, mixed>>, count: int, categories: array<string, int>, funnel_coverage: array<string, bool>} quickStartEvents()
 * @method static list<array{name: string, class: class-string, ga4: string, category: string}> plgEvents()
 * @method static void signUp(?string $method = null, array<string, mixed> $params = [])
 * @method static void login(string $userId, ?string $clientId = null, ?string $method = null, array<string, mixed> $params = [])
 * @method static void trialStart(?string $planName = null, ?int $trialDays = null, array<string, mixed> $params = [])
 * @method static void subscription(?string $planName = null, ?float $amount = null, string $currency = 'USD', ?string $billingCycle = null, array<string, mixed> $params = [])
 * @method static void planUpgrade(string $fromPlan, string $toPlan, ?float $priceDifference = null, array<string, mixed> $params = [])
 * @method static void cancellation(?string $planName = null, ?string $reason = null, array<string, mixed> $params = [])
 * @method static void trackSaaSAcquisition(?string $planName = null, ?float $amount = null, string $currency = 'USD', array<string, mixed> $options = [], array<string, mixed> $params = [])
 * @method static array{status: string, version: string, overall_score: int, timestamp: string, subsystems: array<string, mixed>, recommendations: list<array{priority: string, category: string, message: string}>} healthCheck()
 * @method static array{status: string, version: string, providers_configured: int, catalog_size: int} ping()
 * @method static array{score: int, grade: string, details: array{critical_events: array{present: int, total: int, score: int, max_score: int, missing: list<string>}, aarr_categories: int, providers: int, catalog_size: int}} maturityScore()
 * @method static array{checklist: array<string, list<array{event: string, tracked: bool, priority: string}>>, summary: array{total: int, tracked: int, completion: float, gaps: list<string>}} onboardingChecklist()
 * @method static array{signup_funnel: array{steps: int, present: int, missing: list<string>, score: float}, purchase_funnel: array{steps: int, present: int, missing: list<string>, score: float}, subscription_funnel: array{steps: int, present: int, missing: list<string>, score: float}, overall: float} funnelReadiness()
 * @method static array{pipeline: string, status: string, started_at: string, steps: int, completed_steps: int, identity: string} orchestrate(string $pipelineName, string $clientId, ?string $userId = null, array $params = [])
 * @method static array{step: string, event: string, pipeline_status: string, completed_steps: list<string>, remaining_steps: int, is_complete: bool} orchestrateAdvance(string $pipelineName, string $stepName, string $clientId, ?string $userId = null, array $params = [])
 * @method static float orchestrateProgress(string $pipelineName, string $clientId, ?string $userId = null)
 * @method static array{generated_at: string, insights: list<array{type: string, category: string, title: string, description: string, severity: string, metric: string|null, value: mixed|null, recommendation: string|null}>, summary: array{total: int, by_type: array<string, int>, by_severity: array<string, int>}} insightReport()
 * @method static array{score: float, grade: string, activation: float, engagement: float, retention: float, feature_breadth: float, segment: string, signals: list<string>, identity: string, computed_at: string} plgScore(string $identity)
 * @method static array{avg_score: float, total_cached: int, grade_distribution: array<string, int>} plgAggregate()
 * @method static void plgInvalidate(string $identity)
 * @method static array{total_events: int, unique_identities: int, top_events: list<array{event: string, count: int}>, category_breakdown: array<string, int>, trend: array{direction: string, change_pct: float, current: int, previous: int}, moving_avg: float, period: string, computed_at: string} timeSeries(string $period = '1h')
 * @method static array<string, array{total_events: int, unique_identities: int, top_events: list<array{event: string, count: int}>, category_breakdown: array<string, int>, trend: array, moving_avg: float, period: string}> timeSeriesDashboard()
 * @method static array{current: array, previous: array, delta: array{events: int, identities: int, pct_change: float}} timeSeriesCompare(string $currentPeriod, string $previousPeriod)
 * @method static void group(string $groupId, array<string, mixed> $traits = [], array<string, mixed> $params = [])
 * @method static void groupAddMember(string $userId, string $groupId, string|null $role = null, array<string, mixed> $traits = [])
 * @method static array{group_id: string, traits: array<string, mixed>, member_count: int, updated_at: string|null} getGroup(string $groupId)
 *
 * E-Commerce Shorthand Methods (v26.0.0)
 * @method static void viewItem(array<string, mixed> $item, array<string, mixed> $params = [])
 * @method static void addToCart(array<string, mixed> $item, array<string, mixed> $params = [])
 * @method static void removeFromCart(array<string, mixed> $item, array<string, mixed> $params = [])
 * @method static void viewCart(list<array<string, mixed>> $items = [], float|null $value = null, array<string, mixed> $params = [])
 * @method static void beginCheckout(list<array<string, mixed>> $items = [], float|null $value = null, array<string, mixed> $params = [])
 * @method static void addPaymentInfo(string|null $paymentType = null, array<string, mixed> $params = [])
 * @method static void refund(string $transactionId, float $value, array<string, mixed> $params = [])
 * @method static void abandonedCart(list<array<string, mixed>> $items = [], float|null $value = null, array<string, mixed> $params = [])
 * @method static void checkoutAbandon(int|null $step = null, array<string, mixed> $params = [])
 * @method static void checkoutStep(int $step, string|null $stepName = null, array<string, mixed> $params = [])
 *
 * Engagement Shorthand Methods (v26.0.0)
 * @method static void scrollDepth(int $percent, string|null $url = null, array<string, mixed> $params = [])
 * @method static void click(string $target, string|null $url = null, array<string, mixed> $params = [])
 * @method static void formStart(string|null $formId = null, string|null $formName = null, array<string, mixed> $params = [])
 * @method static void formSubmit(string|null $formId = null, string|null $formName = null, bool|null $success = null, array<string, mixed> $params = [])
 * @method static void search(string $query, int|null $resultsCount = null, array<string, mixed> $params = [])
 * @method static void share(string $method, string|null $contentType = null, string|null $itemId = null, array<string, mixed> $params = [])
 * @method static void outboundClick(string $url, string|null $label = null, array<string, mixed> $params = [])
 * @method static void contentEngagement(string $contentType, string|null $contentId = null, int|null $durationSeconds = null, array<string, mixed> $params = [])
 * @method static void onboardingStep(int $step, string|null $stepName = null, array<string, mixed> $params = [])
 * @method static void onboardingCompleted(int|null $totalSteps = null, array<string, mixed> $params = [])
 * @method static void goalConversion(string $goalName, float|null $value = null, array<string, mixed> $params = [])
 * @method static void feedback(string $type, int|string|null $score = null, array<string, mixed> $params = [])
 * @method static void featureRequest(string $featureName, array<string, mixed> $params = [])
 *
 * SaaS Lifecycle Shorthand Methods (v26.0.0)
 * @method static void subscriptionPaused(string|null $planName = null, array<string, mixed> $params = [])
 * @method static void subscriptionResumed(string|null $planName = null, array<string, mixed> $params = [])
 * @method static void planChanged(string $fromPlan, string $toPlan, array<string, mixed> $params = [])
 * @method static void teamCreated(string|null $teamName = null, int|null $memberCount = null, array<string, mixed> $params = [])
 * @method static void teamMemberJoined(string|null $role = null, string|null $inviteMethod = null, array<string, mixed> $params = [])
 * @method static void teamMemberRemoved(string|null $role = null, array<string, mixed> $params = [])
 * @method static void roleChanged(string $fromRole, string $toRole, array<string, mixed> $params = [])
 * @method static void paymentFailed(string|null $reason = null, float|null $amount = null, array<string, mixed> $params = [])
 * @method static void paymentSucceeded(float|null $amount = null, string|null $method = null, array<string, mixed> $params = [])
 * @method static void milestoneReached(string $milestoneName, array<string, mixed> $params = [])
 * @method static void workspaceCreated(string|null $workspaceName = null, array<string, mixed> $params = [])
 * @method static void usageQuotaReached(string $quotaType, int|null $limit = null, array<string, mixed> $params = [])
 * @method static void billingRetry(int|null $attemptNumber = null, array<string, mixed> $params = [])
 *
 * SaaS Account Lifecycle Shorthand Methods (v101.0.0)
 * @method static void accountActivated(string|null $method = null, array<string, mixed> $params = [])
 * @method static void accountDeactivated(string|null $reason = null, array<string, mixed> $params = [])
 * @method static void featureUsed(string $featureName, string|null $category = null, array<string, mixed> $params = [])
 * @method static void emailVerified(string|null $method = null, array<string, mixed> $params = [])
 * @method static void passwordChanged(string|null $method = null, array<string, mixed> $params = [])
 * @method static void profileUpdated(list<string>|null $fields = null, array<string, mixed> $params = [])
 * @method static void apiRateLimited(string|null $endpoint = null, int|null $limit = null, array<string, mixed> $params = [])
 * @method static void invoiceGenerated(float|null $amount = null, string|null $invoiceId = null, array<string, mixed> $params = [])
 * @method static void accountDeleted(string|null $reason = null, array<string, mixed> $params = [])
 * @method static void dataErasureCompleted(string|null $requestId = null, array<string, mixed> $params = [])
 * @method static void firstValue(string $eventName, array<string, mixed> $params = [])
 * @method static void growthMilestone(string $milestone, array<string, mixed> $params = [])
 *
 * Unified Category Dispatchers (v126.0.0)
 * @method static bool trackEcommerceEvent(string $eventName, array<string, mixed> $params = [], array{currency?: string, value?: float, transaction_id?: string, items?: array<int, array<string, mixed>>} $options = [])
 * @method static bool trackSaaSLifecycle(string $eventName, array<string, mixed> $params = [])
 * @method static bool trackEngagement(string $eventName, array<string, mixed> $params = [])
 * @method static bool trackByCategory(string $eventName, array<string, mixed> $params = [])
 *
 * Identity + Event (v145.0.0)
 * @method static void identifyAndTrack(string $userId, string $eventName, string|null $clientId = null, array<string, mixed> $params = [], array<string, mixed> $traits = [])
 *
 * Native Identify Methods (v258.0.0)
 * @method static array<string, bool> identifyAll(string $userId, array<string, mixed> $traits = [])
 * @method static array<string, bool> identifyTo(string $userId, list<string> $providers, array<string, mixed> $traits = [])
 *
 * Additional Engagement Convenience Methods (v145.0.0)
 * @method static void webVitals(string $metricName, float|int $value, array<string, mixed> $params = [])
 * @method static void jsError(string $message, string|null $source = null, int|null $line = null, int|null $col = null, array<string, mixed> $params = [])
 * @method static void timing(string $category, string $variable, int|float $valueMs, array<string, mixed> $params = [])
 * @method static void sessionStart(string|null $sessionId = null, array<string, mixed> $params = [])
 * @method static void sessionEnd(string|null $sessionId = null, int|null $durationSeconds = null, array<string, mixed> $params = [])
 * @method static void elementVisibility(string $elementId, string|null $elementType = null, bool|null $isVisible = null, array<string, mixed> $params = [])
 * @method static void copyText(string $text, string|null $source = null, array<string, mixed> $params = [])
 * @method static void hover(string $elementId, int|null $durationMs = null, array<string, mixed> $params = [])
 * @method static void clientError(string $message, string|null $type = null, string|null $source = null, array<string, mixed> $params = [])
 *
 * Additional SaaS Lifecycle Convenience Methods (v145.0.0)
 * @method static void consentGrant(array<string, bool>|null $purposes = null, array<string, mixed> $params = [])
 * @method static void consentWithdraw(array<string, bool>|null $purposes = null, array<string, mixed> $params = [])
 * @method static void paymentMethodAdded(string|null $method = null, string|null $provider = null, array<string, mixed> $params = [])
 * @method static void creditApplied(float|null $amount = null, string|null $reason = null, array<string, mixed> $params = [])
 * @method static void featureLimitReached(string $feature, string|null $limitType = null, int|float|null $currentValue = null, int|float|null $limitValue = null, array<string, mixed> $params = [])
 * @method static void integrationFailed(string $integration, string|null $errorType = null, array<string, mixed> $params = [])
 *
 * Revenue Attribution Dashboard (v148.0.0)
 * @method static array{generated_at: string, period_days: int, currency: string, total_revenue: float, total_customers: int, channels: array<string, array{revenue: float, customers: int, ltv: float, cac: float|null, payback_months: float|null, revenue_share: float, avg_revenue_per_customer: float}>, top_channel: string|null, revenue_concentration: float, recommendations: list<string>} revenueAttributionDashboard(?int $lookbackDays = null)
 * @method static array<string, float> ltvByChannel(int $days = 30)
 * @method static array<string, array{spend: float, revenue: float, customers: int, cac: float, cac_recovery_pct: float, payback_months: float|null}> cacRecoveryByChannel(int $days = 30)
 * @method static array{hhi: float, concentration_grade: string, dominant_channel: string|null, risk_level: string} revenueConcentrationAnalysis(int $days = 30)
 * @method static array<string, array{current: float, previous: float, growth_pct: float, growth_abs: float}> channelGrowthTrend(int $days = 30)
 *
 * Context & Wire Protocol Methods (v41.0.0)
 * @method static mixed contextMeasure(string $label, \Closure $callback)
 * @method static \ZeroBoiler\Analytics\Support\AnalyticsContext createContext(string $label, ?string $source = null)
 * @method static string wireSerialize(\ZeroBoiler\Analytics\DTO\AnalyticsEvent $event, array<string, mixed> $metadata = [])
 * @method static string wireSerializeBatch(list<\ZeroBoiler\Analytics\DTO\AnalyticsEvent> $events, array<string, mixed> $metadata = [])
 * @method static \ZeroBoiler\Analytics\DTO\AnalyticsEvent wireDeserialize(string $payload)
 * @method static list<\ZeroBoiler\Analytics\DTO\AnalyticsEvent> wireDeserializeBatch(string $payload)
 * @method static array{valid: bool, errors: list<string>, warnings: list<string>, event_count: int} wireValidate(string $payload)
 * @method static \ZeroBoiler\Analytics\Support\TypedEventBuilder typedEvent(string $name)
 * @method static \ZeroBoiler\Analytics\Support\TypedEventBuilder typedCatalogEvent(string $name)
 * @method static \ZeroBoiler\Analytics\Services\AutoInstrumentationEngine autoInstrument()
 *
 * Privacy & Correlation Methods (v42.0.0)
 * @method static float addPrivacyNoise(float $value, ?float $delta = null)
 * @method static int|null anonymizeCount(int $count, int $k = 10)
 * @method static float addPrivacyNoiseToPercentage(float $percentage, ?int $populationSize = null)
 * @method static float addPrivacyNoiseToRevenue(float $amount, ?float $maxContribution = null)
 * @method static array{head: string, body: string, init: string, providers: list<string>} snippet(array<string, mixed> $options = [])
 * @method static array{providers: list<array{name: string, configured: bool, id_masked: string|null}>} snippetProviderSummary()
 *
 * Testing assertions (when swapped with AnalyticsFake):
 * @method static void assertTracked(string $eventName, ?callable $callback = null)
 * @method static void assertNotTracked(string $eventName)
 * @method static void assertTrackedTimes(string $eventName, int $times)
 * @method static void assertNothingTracked()
 * @method static void assertIdentified(string $userId, ?callable $callback = null)
 * @method static void assertPageViewTracked(?callable $callback = null)
 *
 * @see \\ZeroBoiler\\Analytics\\AnalyticsManager
 * @see \\ZeroBoiler\\Analytics\\Support\\AnalyticsFake
 *
 * @since 1.0.0
 */
final class Analytics extends Facade
{
    protected static function getFacadeAccessor(): string
    {
        return 'zeroboiler.analytics';
    }
}
